In [137]:
import json
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [138]:
file_path = "/Users/alyssanguyen/Desktop/IRLE_scraping/scripts/raw_prices_ubereats_nonca_fflocalunique_090182024.csv"
ca_ff = pd.read_csv(file_path)
file_path_2 = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/uszips.csv"
ca_zip_count = pd.read_csv(file_path_2)
# file_path_3 = "/Users/alyssanguyen/Desktop/IRLE_scraping/csv_files/processed_prices_ubereats_ca_ff_03222024.csv"
# example = pd.read_csv(file_path_3)

In [139]:
#Drop all the columns we don't need 
ca_ff_ = ca_ff.drop(columns=['Unnamed: 0', 'inputted_location','restaurant_distance'])
ca_ff_ = ca_ff_.dropna(subset=['restaurant_location'])

In [140]:
ca_zip_count = ca_zip_count[['zip', 'county_name']]

In [141]:
ca_ff_

,restaurant_name,menu_item,menu_item_price,restaurant_location,restaurant_rating,number_of_ratings
0,Big Mouth Burgers,Shake,9.95,"3392 24th St, San Francisco, CA, 94110, US",4.7,500+
1,Big Mouth Burgers,The Giants Burger,19.95,"3392 24th St, San Francisco, CA, 94110, US",4.7,500+
2,Big Mouth Burgers,The Hangover Burger,19.95,"3392 24th St, San Francisco, CA, 94110, US",4.7,500+
3,Big Mouth Burgers,Big Mouth Burger,15.95,"3392 24th St, San Francisco, CA, 94110, US",4.7,500+
4,Big Mouth Burgers,The Turkey Burger,15.95,"3392 24th St, San Francisco, CA, 94110, US",4.7,500+
...,...,...,...,...,...,...
26022,Burger King,Buffalo Dipping Sauce,0.25,"909 South Main Street, SALINAS, CA, 93901-2404...",4.4,160+
26023,Burger King,Honey Mustard Dipping Sauce,0.25,"909 South Main Street, SALINAS, CA, 93901-2404...",4.4,160+
26024,Burger King,Hidden Valley Ranch Dipping Sauce,0.30,"909 South Main Street, SALINAS, CA, 93901-2404...",4.4,160+
26025,Burger King,Sweet &amp; Sour Dipping Sauce,0.25,"909 South Main Street, SALINAS, CA, 93901-2404...",4.4,160+
26026,Burger King,Zesty Dipping Sauce,0.25,"909 South Main Street, SALINAS, CA, 93901-2404...",4.4,160+

In [142]:
#restaurant_rating cleaning 
# Ensure the column is of string type using .loc
ca_ff_.loc[:, 'restaurant_rating'] = ca_ff_['restaurant_rating'].astype(str)

# Count rows containing 'mi'
rows_with_mi = ca_ff_['restaurant_rating'].str.contains('mi').sum()
print("Number of rows with 'mi' in restaurant rating:", rows_with_mi)

# Replace invalid ratings ending with 'mi' with '0' using .loc
ca_ff_.loc[:, 'restaurant_rating'] = ca_ff_['restaurant_rating'].str.replace(r'.*mi$', '0', regex=True)
ca_ff_['restaurant_rating'] = pd.to_numeric(ca_ff_['restaurant_rating'].str.strip(), errors='coerce')

Number of rows with 'mi' in restaurant rating: 0

In [143]:
#converting data types 
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].astype('string')
ca_ff_['menu_item'] = ca_ff_['menu_item'].astype('string')
ca_ff_['menu_item'] = ca_ff_['menu_item'].str.replace(r'\s+', ' ', regex=True)
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].astype('string')

In [144]:
#cleaning up string columns 

ca_ff_['menu_item'] = ca_ff_['menu_item'].str.lower()
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].str.lower()
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].str.replace('_', ' ')

#remove special characters
ca_ff_['menu_item'] = ca_ff_['menu_item'].apply(lambda x: ''.join(ch for ch in x if ch.isalnum() or ch.isspace()))
ca_ff_#cleaning up string columns 

ca_ff_['menu_item'] = ca_ff_['menu_item'].str.lower()
ca_ff_['restaurant_location'] = ca_ff_['restaurant_location'].str.lower()
ca_ff_['restaurant_name'] = ca_ff_['restaurant_name'].str.replace('_', ' ')

#remove special characters
ca_ff_['menu_item'] = ca_ff_['menu_item'].apply(lambda x: ''.join(ch for ch in x if ch.isalnum() or ch.isspace()))
ca_ff_['restaurant_name'].unique()

<StringArray>
[   'Big Mouth Burgers',       'Burger Station',         'Super Burger',
        'Burger Basket',       'Burger Factory', 'Cypress Best Burgers',
 'Gold Star Hamburgers',          'Hook Burger',        'Burger Palace',
      'Varsity Burgers',          'Burger Boss',        'P & G Burgers',
            'R Burgers',        'Betty Burgers',          'Burger King']
Length: 15, dtype: string

In [145]:
def price_list(x):
    return list(x)

def mean_non_zero(x):
    return np.mean(x[x != 0]) if np.any(x != 0) else 0

def median_non_zero(x):
    return np.median(x[x != 0]) if np.any(x != 0) else 0

def std_non_zero(x):
    return np.std(x[x != 0]) if np.any(x != 0) else 0

In [146]:
#"BJ'S"

ca_ff_bj = ca_ff_[ca_ff_['restaurant_name'] == 'B&J']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_bj = ca_ff_bj.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_bj.columns = [' '.join(col).strip() for col in grouped_bj.columns.values]

In [147]:
grouped_bj

Empty DataFrame
Columns: [restaurant_name, restaurant_location, menu_item_price mean_non_zero, menu_item_price median_non_zero, menu_item_price std_non_zero, restaurant_rating mean, menu_item count, number_of_ratings first]
Index: []

In [148]:
#Second part of grouping 
bj_lst = ['burger','french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_bj = ca_ff_bj[ca_ff_bj['menu_item'].isin(bj_lst)].sort_values('menu_item')
menu_items_bj = menu_items_bj.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_bj_2 = menu_items_bj.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_bj_2[['hamburger','fries']] = grouped_bj_2['menu_item_price'].apply(pd.Series)
grouped_bj_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_bj = pd.merge(grouped_bj, grouped_bj_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_bj['combo'] = np.nan
merged_bj['specialty_item'] = np.nan
merged_bj['cheeseburger'] = np.nan

merged_bj

ValueError: Columns must be same length as key

In [149]:
menu_items_bj

Empty DataFrame
Columns: [restaurant_name, menu_item, menu_item_price, restaurant_location, restaurant_rating, number_of_ratings]
Index: []

In [150]:
#"Barney's Gourmet Hamburgers"

ca_ff_bm = ca_ff_[ca_ff_['restaurant_name'] == 'Big Mouth Burgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_bm = ca_ff_bm.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_bm.columns = [' '.join(col).strip() for col in grouped_bm.columns.values]

In [151]:
#Second part of grouping 
bm_lst = ['big mouth burger', 'blue cheeseburger', 'french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_bm = ca_ff_bm[ca_ff_bm['menu_item'].isin(bm_lst)].sort_values('menu_item')
menu_items_bm = menu_items_bm.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_bm_2 = menu_items_bm.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_bm_2[['hamburger', 'cheeseburger', 'fries']] = grouped_bm_2['menu_item_price'].apply(pd.Series)
grouped_bm_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_bm = pd.merge(grouped_bm, grouped_bm_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_bm['combo'] = np.nan
merged_bm['specialty_item'] = np.nan
merged_bm

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,hamburger,cheeseburger,fries,combo,specialty_item
0,Big Mouth Burgers,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,4.48,NaN,NaN,NaN,NaN
1,Big Mouth Burgers,"1117 e commonwealth ave, fullerton, ca, 92831, us",10.800485,11.24,3.878176,4.9,103,600+,4.61,NaN,NaN,NaN,NaN
2,Big Mouth Burgers,"1302 soquel avenue, santa cruz, ca, 95062, us",7.774655,6.23,5.266467,4.4,116,400+,4.74,NaN,NaN,NaN,NaN
3,Big Mouth Burgers,"190 west valley boulevard, colton, ca, 92324, us",11.066235,10.79,5.469740,4.6,174,2,6.99,NaN,NaN,NaN,NaN
4,Big Mouth Burgers,"3392 24th st, san francisco, ca, 94110, us",14.578571,15.95,4.517178,4.7,35,500+,15.95,17.95,4.95,NaN,NaN
5,Big Mouth Burgers,"441 w duarte rd, monrovia, ca, 91016, us",15.003643,17.99,5.543355,4.8,129,1,7.99,NaN,NaN,NaN,NaN
6,Big Mouth Burgers,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,73,3,5.80,NaN,NaN,NaN,NaN
7,Big Mouth Burgers,"851 cherry ave, san bruno, ca, 94066, us",15.280952,16.95,4.420380,4.8,42,800+,15.95,17.95,5.25,NaN,NaN

In [152]:
#'Burger Station'

ca_ff_bs = ca_ff_[ca_ff_['restaurant_name'] == 'Burger Station']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_bs = ca_ff_bs.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_bs.columns = [' '.join(col).strip() for col in grouped_bs.columns.values]

In [153]:
#Second part of grouping 
bs_lst = ['cheese burger', 'earth burger', 'french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_bs = ca_ff_bs[ca_ff_bs['menu_item'].isin(bs_lst)].sort_values('menu_item')
menu_items_bs = menu_items_bs.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_bs_2 = menu_items_bs.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_bs_2[['cheeseburger', 'hamburger', 'fries']] = grouped_bs_2['menu_item_price'].apply(pd.Series)
grouped_bs_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_bs = pd.merge(grouped_bs, grouped_bs_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_bs['combo'] = np.nan
merged_bs['specialty_item'] = np.nan


merged_bs

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,hamburger,fries,combo,specialty_item
0,Burger Station,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,4.48,NaN,NaN,NaN,NaN
1,Burger Station,"1117 e commonwealth ave, fullerton, ca, 92831, us",10.800485,11.24,3.878176,4.9,103,600+,4.61,NaN,NaN,NaN,NaN
2,Burger Station,"190 west valley boulevard, colton, ca, 92324, us",11.066235,10.79,5.469740,4.6,174,2,6.99,NaN,NaN,NaN,NaN
3,Burger Station,"2845 mission street, san francisco, ca, 94110, us",12.137647,11.99,4.275164,4.6,17,110+,11.99,NaN,NaN,NaN,NaN
4,Burger Station,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,73,3,5.80,NaN,NaN,NaN,NaN
5,Burger Station,"603 saratoga avenue, suite 30, san jose, ca, 9...",15.606667,14.49,10.873273,4.7,90,460+,12.99,11.99,6.99,NaN,NaN
6,Burger Station,"969 south glendora avenue, ste c, west covina,...",11.473256,12.99,4.033325,4.5,129,120+,4.55,NaN,NaN,NaN,NaN

In [154]:
#'Super Burger'

ca_ff_sb = ca_ff_[ca_ff_['restaurant_name'] == 'Super Burger']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_sb = ca_ff_sb.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_sb.columns = [' '.join(col).strip() for col in grouped_sb.columns.values]

In [155]:
#Second part of grouping 
sb_lst = ['fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_sb = ca_ff_sb[ca_ff_sb['menu_item'].isin(sb_lst)].sort_values('menu_item')
menu_items_sb = menu_items_sb.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_sb_2 = menu_items_sb.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_sb_2[['fries']] = grouped_sb_2['menu_item_price'].apply(pd.Series)
grouped_sb_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_sb = pd.merge(grouped_sb, grouped_sb_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_sb['combo'] = np.nan
merged_sb['specialty_item'] = np.nan
merged_sb['cheeseburger'] = np.nan
merged_sb['hamburger'] = np.nan


merged_sb

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,fries,combo,specialty_item,cheeseburger,hamburger
0,Super Burger,"1340 coffee rd, modesto, ca, 95355, us",9.772667,9.99,3.122067,4.2,75,110+,4.69,NaN,NaN,NaN,NaN
1,Super Burger,"1623 s brand blvd, glendale, ca, 91204, us",10.903143,10.84,5.021796,4.9,70,700+,5.25,NaN,NaN,NaN,NaN
2,Super Burger,"1666 university avenue, riverside, ca, 92507, us",12.824778,12.79,5.440561,4.6,91,440+,4.99,NaN,NaN,NaN,NaN
3,Super Burger,"23750 alessandro boulevard suite b, moreno val...",12.232727,11.69,5.424566,4.6,78,270+,4.99,NaN,NaN,NaN,NaN
4,Super Burger,"4890 south motor lane, ontario, ca, 91761, us",12.840556,12.79,5.440741,4.5,91,230+,4.99,NaN,NaN,NaN,NaN
5,Super Burger,"5831 s santa fe ave, vernon, ca, 90058, us",11.423444,11.99,4.071488,4.8,90,290+,4.99,NaN,NaN,NaN,NaN

In [156]:
#'Burger Basket'

ca_ff_basket = ca_ff_[ca_ff_['restaurant_name'] == 'Burger Basket']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_basket = ca_ff_basket.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_basket.columns = [' '.join(col).strip() for col in grouped_basket.columns.values]

In [157]:
#Second part of grouping 
basket_lst = ['cheeseburger','french fries', 'hamburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_basket = ca_ff_basket[ca_ff_basket['menu_item'].isin(basket_lst)].sort_values('menu_item')
menu_items_basket = menu_items_basket.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_basket_2 = menu_items_basket.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_basket_2[['cheeseburger','fries', 'hamburger']] = grouped_basket_2['menu_item_price'].apply(pd.Series)
grouped_basket_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_basket = pd.merge(grouped_basket, grouped_basket_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_basket['combo'] = np.nan
merged_basket['specialty_item'] = np.nan
#merged_basket['cheeseburger'] = np.nan

merged_basket

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,hamburger,combo,specialty_item
0,Burger Basket,"100 e manchester ave, los angeles, ca, 90003, us",9.234722,9.20,4.972100,4.6,108,440+,5.75,NaN,NaN,NaN,NaN
1,Burger Basket,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,4.48,11.95,NaN,NaN,NaN
2,Burger Basket,"1117 e commonwealth ave, fullerton, ca, 92831, us",10.800485,11.24,3.878176,4.9,103,600+,4.61,NaN,NaN,NaN,NaN
3,Burger Basket,"1623 s brand blvd, glendale, ca, 91204, us",10.903143,10.84,5.021796,4.9,70,700+,8.29,7.89,NaN,NaN,NaN
4,Burger Basket,"1886 villa ave, clovis, ca, 93612, us",9.950000,8.49,4.879057,4.3,50,140+,4.19,NaN,NaN,NaN,NaN
5,Burger Basket,"190 west valley boulevard, colton, ca, 92324, us",11.066235,10.79,5.469740,4.6,174,2,6.99,NaN,NaN,NaN,NaN
6,Burger Basket,"27700 santa margarita pky, mission viejo, ca, ...",6.651513,4.79,5.245001,4.6,133,1,4.07,3.59,NaN,NaN,NaN
7,Burger Basket,"2845 mission street, san francisco, ca, 94110, us",12.137647,11.99,4.275164,4.6,17,110+,11.99,NaN,NaN,NaN,NaN
8,Burger Basket,"310 e 17th st, costa mesa, ca, 92627, us",5.812000,5.55,3.148743,4.8,25,600+,5.55,4.85,NaN,NaN,NaN
9,Burger Basket,"3500 w ball rd, anaheim, ca, 92804, us",9.985600,9.50,5.869771,4.8,125,350+,7.25,6.75,NaN,NaN,NaN
10,Burger Basket,"441 w duarte rd, monrovia, ca, 91016, us",15.003643,17.99,5.543355,4.8,129,1,7.99,NaN,NaN,NaN,NaN
11,Burger Basket,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,73,3,7.85,5.80,7.35,NaN,NaN

In [158]:
#'Burger Factory'

ca_ff_factory = ca_ff_[ca_ff_['restaurant_name'] == 'Burger Factory']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_factory = ca_ff_factory.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_factory.columns = [' '.join(col).strip() for col in grouped_factory.columns.values]

In [159]:
#Second part of grouping 
factory_lst = ['colossal burger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_factory = ca_ff_factory[ca_ff_factory['menu_item'].isin(factory_lst)].sort_values('menu_item')
menu_items_factory = menu_items_factory.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_factory_2 = menu_items_factory.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_factory_2[['hamburger']] = grouped_factory_2['menu_item_price'].apply(pd.Series)
grouped_factory_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_factory = pd.merge(grouped_factory, grouped_factory_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_factory['combo'] = np.nan
merged_factory['specialty_item'] = np.nan
merged_factory['cheeseburger'] = np.nan
merged_factory['fries'] = np.nan


merged_factory

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,hamburger,combo,specialty_item,cheeseburger,fries
0,Burger Factory,"1358 w martin luther king jr blvd, los angeles...",12.010795,12.50,6.748854,4.5,440,700+,9.00,NaN,NaN,NaN,NaN
1,Burger Factory,"1666 university avenue, riverside, ca, 92507, us",12.824778,12.79,5.440561,4.6,91,440+,13.99,NaN,NaN,NaN,NaN
2,Burger Factory,"4890 south motor lane, ontario, ca, 91761, us",12.840556,12.79,5.440741,4.5,91,230+,13.99,NaN,NaN,NaN,NaN

In [160]:
#'Cypress Best Burgers'

ca_ff_cypress = ca_ff_[ca_ff_['restaurant_name'] == 'Cypress Best Burgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_cypress = ca_ff_cypress.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_cypress.columns = [' '.join(col).strip() for col in grouped_cypress.columns.values]

In [161]:
#Second part of grouping 
cypress_lst = ['french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_cypress = ca_ff_cypress[ca_ff_cypress['menu_item'].isin(cypress_lst)].sort_values('menu_item')
menu_items_cypress = menu_items_cypress.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_cypress_2 = menu_items_cypress.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_cypress_2[['fries']] = grouped_cypress_2['menu_item_price'].apply(pd.Series)
grouped_cypress_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_cypress = pd.merge(grouped_cypress, grouped_cypress_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_cypress['combo'] = np.nan
merged_cypress['specialty_item'] = np.nan
merged_cypress['hamburger'] = np.nan
merged_cypress['cheeseburger'] = np.nan



merged_cypress

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,fries,combo,specialty_item,hamburger,cheeseburger
0,Cypress Best Burgers,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,4.48,NaN,NaN,NaN,NaN
1,Cypress Best Burgers,"1117 e commonwealth ave, fullerton, ca, 92831, us",10.800485,11.24,3.878176,4.9,103,600+,4.61,NaN,NaN,NaN,NaN
2,Cypress Best Burgers,"1400 ocean st, santa cruz, ca, 95060, us",12.015875,8.99,11.023823,4.5,80,1,4.86,NaN,NaN,NaN,NaN
3,Cypress Best Burgers,"190 west valley boulevard, colton, ca, 92324, us",11.066235,10.79,5.469740,4.6,174,2,6.99,NaN,NaN,NaN,NaN
4,Cypress Best Burgers,"2845 mission street, san francisco, ca, 94110, us",12.137647,11.99,4.275164,4.6,17,110+,11.99,NaN,NaN,NaN,NaN
5,Cypress Best Burgers,"2900 east whitmore avenue, ceres, ca, 95307, us",11.274430,8.61,10.430992,4.7,79,170+,4.36,NaN,NaN,NaN,NaN
6,Cypress Best Burgers,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,73,3,5.80,NaN,NaN,NaN,NaN

In [162]:
#'Gold Star Hamburgers'

ca_ff_gold = ca_ff_[ca_ff_['restaurant_name'] == 'Gold Star Hamburgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_gold = ca_ff_gold.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_gold.columns = [' '.join(col).strip() for col in grouped_gold.columns.values]

In [163]:
#Second part of grouping 
gold_lst = ['cheeseburger', 'fries','hamburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_gold = ca_ff_gold[ca_ff_gold['menu_item'].isin(gold_lst)].sort_values('menu_item')
menu_items_gold = menu_items_gold.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_gold_2 = menu_items_gold.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_gold_2[['cheeseburger', 'fries', 'hamburger']] = grouped_gold_2['menu_item_price'].apply(pd.Series)
grouped_gold_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_gold = pd.merge(grouped_gold, grouped_gold_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_gold['combo'] = np.nan
merged_gold['specialty_item'] = np.nan


merged_gold

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,hamburger,combo,specialty_item
0,Gold Star Hamburgers,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,11.95,NaN,NaN,NaN,NaN
1,Gold Star Hamburgers,"1101 pacific avenue, santa cruz, ca, 95060, us",8.998000,9.59,3.495680,4.6,30,800+,14.39,13.19,NaN,NaN,NaN
2,Gold Star Hamburgers,"1340 coffee rd, modesto, ca, 95355, us",9.772667,9.99,3.122067,4.2,75,110+,4.69,NaN,NaN,NaN,NaN
3,Gold Star Hamburgers,"1623 s brand blvd, glendale, ca, 91204, us",10.903143,10.84,5.021796,4.9,490,700+,8.29,5.25,7.89,NaN,NaN
4,Gold Star Hamburgers,"3500 w ball rd, anaheim, ca, 92804, us",9.985600,9.50,5.869771,4.8,125,350+,7.25,6.75,NaN,NaN,NaN
5,Gold Star Hamburgers,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,73,3,7.85,7.35,NaN,NaN,NaN

In [164]:
#'Hook Burger'

ca_ff_hook = ca_ff_[ca_ff_['restaurant_name'] == 'Hook Burger']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_hook = ca_ff_hook.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_hook.columns = [' '.join(col).strip() for col in grouped_hook.columns.values]

In [165]:
#Second part of grouping 
hook_lst = ['french fries','hook burger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_hook = ca_ff_hook[ca_ff_hook['menu_item'].isin(hook_lst)].sort_values('menu_item')
menu_items_hook = menu_items_hook.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_hook_2 = menu_items_hook.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_hook_2[['fries', 'hamburger']] = grouped_hook_2['menu_item_price'].apply(pd.Series)
grouped_hook_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_hook = pd.merge(grouped_hook, grouped_hook_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_hook['combo'] = np.nan
merged_hook['specialty_item'] = np.nan
merged_hook['cheeseburger'] = np.nan

merged_gold

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,hamburger,combo,specialty_item
0,Gold Star Hamburgers,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,11.95,NaN,NaN,NaN,NaN
1,Gold Star Hamburgers,"1101 pacific avenue, santa cruz, ca, 95060, us",8.998000,9.59,3.495680,4.6,30,800+,14.39,13.19,NaN,NaN,NaN
2,Gold Star Hamburgers,"1340 coffee rd, modesto, ca, 95355, us",9.772667,9.99,3.122067,4.2,75,110+,4.69,NaN,NaN,NaN,NaN
3,Gold Star Hamburgers,"1623 s brand blvd, glendale, ca, 91204, us",10.903143,10.84,5.021796,4.9,490,700+,8.29,5.25,7.89,NaN,NaN
4,Gold Star Hamburgers,"3500 w ball rd, anaheim, ca, 92804, us",9.985600,9.50,5.869771,4.8,125,350+,7.25,6.75,NaN,NaN,NaN
5,Gold Star Hamburgers,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,73,3,7.85,7.35,NaN,NaN,NaN

In [166]:
#'Burger Palace'

ca_ff_palace = ca_ff_[ca_ff_['restaurant_name'] == 'Burger Palace']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_palace = ca_ff_palace.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_palace.columns = [' '.join(col).strip() for col in grouped_palace.columns.values]

In [167]:
#Second part of grouping 
palace_lst = ['14 lb hamburger', 'cheeseburger', 'small french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_palace = ca_ff_palace[ca_ff_palace['menu_item'].isin(palace_lst)].sort_values('menu_item')
menu_items_palace = menu_items_palace.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_palace_2 = menu_items_palace.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_palace_2[['hamburger', 'cheeseburger', 'fries']] = grouped_palace_2['menu_item_price'].apply(pd.Series)
grouped_palace_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_palace = pd.merge(grouped_palace, grouped_palace_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_palace['combo'] = np.nan
merged_palace['specialty_item'] = np.nan

merged_palace

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,hamburger,cheeseburger,fries,combo,specialty_item
0,Burger Palace,"100 e manchester ave, los angeles, ca, 90003, us",9.234722,9.2,4.9721,4.6,540,440+,5.2,5.75,3.45,NaN,NaN

In [168]:
#'Varsity Burgers'

ca_ff_varsity = ca_ff_[ca_ff_['restaurant_name'] == 'Varsity Burgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_varsity = ca_ff_varsity.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_varsity.columns = [' '.join(col).strip() for col in grouped_varsity.columns.values]

In [169]:
#Second part of grouping 
varsity_lst = ['cheeseburger', 'french fries', 'hamburger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_varsity = ca_ff_varsity[ca_ff_varsity['menu_item'].isin(varsity_lst)].sort_values('menu_item')
menu_items_varsity = menu_items_varsity.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_varsity_2 = menu_items_varsity.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_varsity_2[['cheeseburger', 'fries','hamburger']] = grouped_varsity_2['menu_item_price'].apply(pd.Series)
grouped_varsity_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_varsity = pd.merge(grouped_varsity, grouped_varsity_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_varsity['combo'] = np.nan
merged_varsity['specialty_item'] = np.nan

merged_varsity

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,fries,hamburger,combo,specialty_item
0,Varsity Burgers,"10361 rockingham drive, sacramento, ca, 95827, us",11.260423,12.93,3.974134,4.8,71,61,4.48,11.95,NaN,NaN,NaN
1,Varsity Burgers,"1623 s brand blvd, glendale, ca, 91204, us",10.903143,10.84,5.021796,4.9,70,700+,8.29,7.89,NaN,NaN,NaN
2,Varsity Burgers,"190 west valley boulevard, colton, ca, 92324, us",11.066235,10.79,5.469740,4.6,174,2,6.99,NaN,NaN,NaN,NaN
3,Varsity Burgers,"2845 mission street, san francisco, ca, 94110, us",12.137647,11.99,4.275164,4.6,17,110+,11.99,NaN,NaN,NaN,NaN
4,Varsity Burgers,"600 w lincoln ave, anaheim, ca, 92805, us",10.043836,9.35,2.468194,4.8,584,3,7.85,5.80,7.35,NaN,NaN

In [170]:
#'Burger Boss'

ca_ff_boss = ca_ff_[ca_ff_['restaurant_name'] == 'Burger Boss']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_boss = ca_ff_boss.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_boss.columns = [' '.join(col).strip() for col in grouped_boss.columns.values]

In [171]:
ca_ff_boss['menu_item'].value_counts().reset_index()['menu_item'][0:50]

0                              french fries
1                          strawberry shake
2                           chocolate shake
3                             vanilla shake
4                                 dr pepper
5                             bottled water
6                                    coffee
7                                    sprite
8                                 diet coke
9                                   classic
10                              canned soda
11                                 original
12                            bacon avocado
13                             cheese fries
14                       chili cheese fries
15                      smoked brisket boss
16                          fresh cut fries
17                          black bean boss
18                       spicy chicken boss
19                     classic chicken boss
20                              turkey boss
21                                 bbq boss
22                               patty melt
23                           grilled cheese
24                            original boss
25                          bistro boss lto
26                         boss your burger
27                             french toast
28                               boss fries
29                            ultimate boss
30                   chocolate chunk cookie
31                    cajun fresh cut fries
32       organic black iced tea unsweetened
33                          blondie brownie
34                        chocolate brownie
35                    salted caramel cookie
36                            caramel shake
37                            babe kombucha
38                          lime topo chico
39                       pineapple jarritos
40                        mandarin jarritos
41                             mexican coke
42    tropical passion iced tea unsweetened
43                           fresh lemonade
44                       sweet potato fries
45                             fanta orange
46                            powerade blue
47                           diet dr pepper
48                                coke zero
49                                     coke
Name: menu_item, dtype: object

In [174]:
#Second part of grouping 
boss_lst = ['french fries','original']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_boss = ca_ff_boss[ca_ff_boss['menu_item'].isin(boss_lst)].sort_values('menu_item')
menu_items_boss = menu_items_boss.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_boss_2 = menu_items_boss.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_boss_2[['fries','cheeseburger']] = grouped_boss_2['menu_item_price'].apply(pd.Series)
grouped_boss_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_boss = pd.merge(grouped_boss, grouped_boss_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_boss['combo'] = np.nan
merged_boss['specialty_item'] = np.nan
merged_boss['hamburger'] = np.nan

merged_boss

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,fries,cheeseburger,combo,specialty_item,hamburger
0,Burger Boss,"190 west valley boulevard, colton, ca, 92324, us",11.066235,10.79,5.469740,4.6,174,2,6.99,NaN,NaN,NaN,NaN
1,Burger Boss,"2845 mission street, san francisco, ca, 94110, us",12.137647,11.99,4.275164,4.6,17,110+,11.99,NaN,NaN,NaN,NaN
2,Burger Boss,"441 w duarte rd, monrovia, ca, 91016, us",15.003643,17.99,5.543355,4.8,129,1,7.99,NaN,NaN,NaN,NaN
3,Burger Boss,"8911 sunset boulevard, west hollywood, ca, 900...",6.203333,6.62,3.191518,4.7,36,110+,4.25,8.99,NaN,NaN,NaN

In [175]:
#'P & G Burgers'

ca_ff_pg = ca_ff_[ca_ff_['restaurant_name'] == 'P & G Burgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_pg = ca_ff_pg.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_pg.columns = [' '.join(col).strip() for col in grouped_pg.columns.values]

In [176]:
#Second part of grouping 
pg_lst = ['burger 14 lb', 'cheeseburger 14 lb', 'french fries']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_pg = ca_ff_pg[ca_ff_pg['menu_item'].isin(pg_lst)].sort_values('menu_item')
menu_items_pg = menu_items_pg.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_pg_2 = menu_items_pg.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_pg_2[['hamburger', 'cheeseburger','fries']] = grouped_pg_2['menu_item_price'].apply(pd.Series)
grouped_pg_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_pg = pd.merge(grouped_pg, grouped_pg_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_pg['combo'] = np.nan
merged_pg['specialty_item'] = np.nan

merged_pg

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,hamburger,cheeseburger,fries,combo,specialty_item
0,P & G Burgers,"143 south el camino real, millbrae, ca, 94030, us",11.783924,8.740,10.912401,4.5,79,600+,4.74,NaN,NaN,NaN,NaN
1,P & G Burgers,"190 west valley boulevard, colton, ca, 92324, us",11.068000,10.790,5.471006,4.6,696,2,5.99,6.99,6.99,NaN,NaN
2,P & G Burgers,"2200 barranca pkwy, irvine, ca, 92606, us",11.425823,8.740,10.651792,4.6,79,1,4.49,NaN,NaN,NaN,NaN
3,P & G Burgers,"23632 el toro rd a, lake forest, ca, 92630, us",11.425823,8.740,10.651792,4.5,79,1,4.49,NaN,NaN,NaN,NaN
4,P & G Burgers,"25948 mcbean parkway, santa clarita, ca, 91355...",12.336579,9.485,11.213886,4.7,76,1,4.86,NaN,NaN,NaN,NaN
5,P & G Burgers,"305 gellert blvd, daly city, ca, 94015, us",12.293924,9.110,11.390425,4.6,79,3,4.99,NaN,NaN,NaN,NaN
6,P & G Burgers,"3050 n tegner road, turlock, ca, 95380, us",14.400429,14.790,9.528721,4.5,165,150+,7.59,NaN,NaN,NaN,NaN

In [177]:
#'R Burgers'

ca_ff_r = ca_ff_[ca_ff_['restaurant_name'] == 'R Burgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_r = ca_ff_r.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_r.columns = [' '.join(col).strip() for col in grouped_r.columns.values]

In [178]:
#Second part of grouping 
r_lst = ['6 double cheeseburger', 'r burger']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_r = ca_ff_r[ca_ff_r['menu_item'].isin(r_lst)].sort_values('menu_item')
menu_items_r = menu_items_r.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_r_2 = menu_items_r.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_r_2[['cheeseburger', 'hamburger']] = grouped_r_2['menu_item_price'].apply(pd.Series)
grouped_r_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_r = pd.merge(grouped_r, grouped_r_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_r['combo'] = np.nan
merged_r['specialty_item'] = np.nan
merged_r['fries'] = np.nan

merged_r

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,cheeseburger,hamburger,combo,specialty_item,fries
0,R Burgers,"1666 university avenue, riverside, ca, 92507, us",12.824778,12.79,5.440561,4.6,182,440+,19.49,11.99,NaN,NaN,NaN
1,R Burgers,"23750 alessandro boulevard suite b, moreno val...",12.232727,11.69,5.424566,4.6,78,270+,19.49,11.99,NaN,NaN,NaN
2,R Burgers,"4890 south motor lane, ontario, ca, 91761, us",12.840556,12.79,5.440741,4.5,182,230+,19.49,11.99,NaN,NaN,NaN
3,R Burgers,"5980 van buren blvd, riverside, ca, 92503, us",12.839889,12.79,5.435684,4.4,182,180+,19.49,11.99,NaN,NaN,NaN

In [179]:
grouped_r_2

,restaurant_name,restaurant_location,cheeseburger,hamburger
0,R Burgers,"1666 university avenue, riverside, ca, 92507, us",19.49,11.99
1,R Burgers,"23750 alessandro boulevard suite b, moreno val...",19.49,11.99
2,R Burgers,"4890 south motor lane, ontario, ca, 91761, us",19.49,11.99
3,R Burgers,"5980 van buren blvd, riverside, ca, 92503, us",19.49,11.99

In [180]:
#'Betty Burgers'

ca_ff_betty = ca_ff_[ca_ff_['restaurant_name'] == 'Betty Burgers']

#First part of grouping 

agg_funcs = {
    'menu_item_price': [mean_non_zero, median_non_zero, std_non_zero],  # calculate the average, median, and standard dev PRICE
    'restaurant_rating': 'mean', # calculate the average RATING 
    'menu_item' : 'count',
    'number_of_ratings': 'first'
}

grouped_betty = ca_ff_betty.groupby(['restaurant_name','restaurant_location']).agg(agg_funcs).reset_index()
grouped_betty.columns = [' '.join(col).strip() for col in grouped_betty.columns.values]

In [181]:
#Second part of grouping 
betty_lst = ['basic betty', 'crispy fries  regular']

# Filter rows where 'menu_item' contains any item in mcd_lst
menu_items_betty = ca_ff_betty[ca_ff_betty['menu_item'].isin(betty_lst)].sort_values('menu_item')
menu_items_betty = menu_items_betty.drop_duplicates(subset=['restaurant_name', 'restaurant_location', 'menu_item'])

grouped_betty_2 = menu_items_betty.groupby(['restaurant_name', 'restaurant_location'])['menu_item_price'].agg(price_list).reset_index()

grouped_betty_2[['hamburger', 'fries']] = grouped_betty_2['menu_item_price'].apply(pd.Series)
grouped_betty_2.drop(columns=['menu_item_price'], inplace=True)

#Merging the grouped dfs together 
merged_betty = pd.merge(grouped_betty, grouped_betty_2, on=['restaurant_name', 'restaurant_location'], how='inner')
merged_betty['combo'] = np.nan
merged_betty['specialty_item'] = np.nan
merged_betty['cheeseburger'] = np.nan

merged_betty

,restaurant_name,restaurant_location,menu_item_price mean_non_zero,menu_item_price median_non_zero,menu_item_price std_non_zero,restaurant_rating mean,menu_item count,number_of_ratings first,hamburger,fries,combo,specialty_item,cheeseburger
0,Betty Burgers,"415 trout gulch road, aptos, ca, 95003, us",10.079400,8.99,5.014637,4.7,116,39,13.49,3.99,NaN,NaN,NaN
1,Betty Burgers,"505 seabright ave, santa cruz, ca, 95062, us",8.660145,7.99,5.298367,4.7,69,72,13.49,3.99,NaN,NaN,NaN

In [182]:
ubereats_fflocal_prices = pd.concat(
    [
        merged_bm, 
        merged_bs, 
        merged_sb, 
        merged_basket, 
        merged_factory, 
        merged_cypress, 
        merged_gold, 
        merged_hook,
        merged_palace,
        merged_varsity,
        merged_boss,
        merged_pg,
        merged_r,
        merged_betty
    ]
).reset_index(drop=True)

In [109]:
ubereats_fflocal_prices = merged_bj

In [183]:
pattern = r",\s*([a-zA-Z]{2})\s*,?\s*(\d{5}(?:-\d{4})?)"

def extract_state_zip(address):
    match = re.search(pattern, address)
    if match:
        state, zip_code = match.groups()
        return state, zip_code
    else:
        return None, None

# Apply the function to extract state and zip code

ubereats_fflocal_prices[['state', 'zip']] = ubereats_fflocal_prices['restaurant_location'].apply(lambda x: pd.Series(extract_state_zip(x)))

ubereats_fflocal_prices['zip'] = ubereats_fflocal_prices['zip'].str.split('-').str[0].astype(int)

#Get county 
ubereats_fflocal_prices = ubereats_fflocal_prices.merge(ca_zip_count, on = 'zip')

In [185]:
specific_date = datetime.strptime('09182024', '%m%d%Y')
# Assign the datetime object to the entire 'date' column
ubereats_fflocal_prices['date'] = specific_date
ubereats_fflocal_prices['uber_eats'] = 1
ubereats_fflocal_prices['post_policy'] = 1
ubereats_fflocal_prices['fast_food'] = 1
ubereats_fflocal_prices['local'] = 1

In [43]:
ubereats_fflocal_prices.to_csv('processed_prices_ubereats_nonca_fflocalunique_09182024.csv', index = True)